Cutlib.o: Cutlib.cpp ../include/Cutlib.h /usr/local/FFV/Polylib/include/Polylib.h \
 /usr/local/FFV/Polylib/include/polygons/Polygons.h \
 /usr/local/FFV/Polylib/include/polygons/VTree.h \
 /usr/local/FFV/Polylib/include/common/BBox.h \
 /usr/local/FFV/Polylib/include/common/Vec2.h \
 /usr/local/FFV/Polylib/include/common/Vec3.h \
 /usr/local/FFV/Polylib/include/common/vec3_func.h \
 /usr/local/FFV/Polylib/include/common/vec3f_func.h \
 /usr/local/FFV/Polylib/include/common/axis.h \
 /usr/local/FFV/Polylib/include/common/PolylibStat.h \
 /usr/local/FFV/Polylib/include/common/PolylibCommon.h \
 /usr/local/FFV/Polylib/include/common/tt.h \
 /usr/local/FFV/Polylib/include/polygons/TriMesh.h \
 /usr/local/FFV/Polylib/include/polygons/Triangle.h \
 /usr/local/FFV/Polylib/include/groups/PolygonGroup.h \
 /usr/local/FFV/TextParser/include/TextParser.h \
 /usr/local/FFV/TextParser/include/TextParserCommon.h \
 /usr/local/FFV/TextParser/include/Version.h \
 /usr/local/FFV/Polylib/include/groups/PolygonGroupFactory.h \
 /usr/local/FFV/Polylib/include/Version.h \
 ../include/RepairPolygonData/RepairPolygonData.h \
 ../include/CutInfo/CutInfoArray.h ../include/CutInfo/CutInfo.h \
 ../include/CutInfo/CutNormalArray.h ../include/Cutlib.h \
 ../include/GridAccessor/GridAccessor.h ../include/Version.h CutSearch.h
CutSearch.o: CutSearch.cpp CutSearch.h ../include/GridAccessor/GridAccessor.h \
 ../include/CutInfo/CutInfo.h ../include/CutInfo/CutInfoArray.h \
 /usr/local/FFV/Polylib/include/Polylib.h \
 /usr/local/FFV/Polylib/include/polygons/Polygons.h \
 /usr/local/FFV/Polylib/include/polygons/VTree.h \
 /usr/local/FFV/Polylib/include/common/BBox.h \
 /usr/local/FFV/Polylib/include/common/Vec2.h \
 /usr/local/FFV/Polylib/include/common/Vec3.h \
 /usr/local/FFV/Polylib/include/common/vec3_func.h \
 /usr/local/FFV/Polylib/include/common/vec3f_func.h \
 /usr/local/FFV/Polylib/include/common/axis.h \
 /usr/local/FFV/Polylib/include/common/PolylibStat.h \
 /usr/local/FFV/Polylib/include/common/PolylibCommon.h \
 /usr/local/FFV/Polylib/include/common/tt.h \
 /usr/local/FFV/Polylib/include/polygons/TriMesh.h \
 /usr/local/FFV/Polylib/include/polygons/Triangle.h \
 /usr/local/FFV/Polylib/include/groups/PolygonGroup.h \
 /usr/local/FFV/TextParser/include/TextParser.h \
 /usr/local/FFV/TextParser/include/TextParserCommon.h \
 /usr/local/FFV/TextParser/include/Version.h \
 /usr/local/FFV/Polylib/include/groups/PolygonGroupFactory.h \
 /usr/local/FFV/Polylib/include/Version.h TargetTriangle.h
TargetTriangle.o: TargetTriangle.cpp TargetTriangle.h \
 /usr/local/FFV/Polylib/include/Polylib.h \
 /usr/local/FFV/Polylib/include/polygons/Polygons.h \
 /usr/local/FFV/Polylib/include/polygons/VTree.h \
 /usr/local/FFV/Polylib/include/common/BBox.h \
 /usr/local/FFV/Polylib/include/common/Vec2.h \
 /usr/local/FFV/Polylib/include/common/Vec3.h \
 /usr/local/FFV/Polylib/include/common/vec3_func.h \
 /usr/local/FFV/Polylib/include/common/vec3f_func.h \
 /usr/local/FFV/Polylib/include/common/axis.h \
 /usr/local/FFV/Polylib/include/common/PolylibStat.h \
 /usr/local/FFV/Polylib/include/common/PolylibCommon.h \
 /usr/local/FFV/Polylib/include/common/tt.h \
 /usr/local/FFV/Polylib/include/polygons/TriMesh.h \
 /usr/local/FFV/Polylib/include/polygons/Triangle.h \
 /usr/local/FFV/Polylib/include/groups/PolygonGroup.h \
 /usr/local/FFV/TextParser/include/TextParser.h \
 /usr/local/FFV/TextParser/include/TextParserCommon.h \
 /usr/local/FFV/TextParser/include/Version.h \
 /usr/local/FFV/Polylib/include/groups/PolygonGroupFactory.h \
 /usr/local/FFV/Polylib/include/Version.h
RepairPolygonData.o: RepairPolygonData.cpp \
 ../include/RepairPolygonData/RepairPolygonData.h \
 /usr/local/FFV/Polylib/include/Polylib.h \
 /usr/local/FFV/Polylib/include/polygons/Polygons.h \
 /usr/local/FFV/Polylib/include/polygons/VTree.h \
 /usr/local/FFV/Polylib/include/common/BBox.h \
 /usr/local/FFV/Polylib/include/common/Vec2.h \
 /usr/local/FFV/Polylib/include/common/Vec3.h \
 /usr/local/FFV/Polylib/include/common/vec3_func.h \
 /usr/local/FFV/Polylib/include/common/vec3f_func.h \
 /usr/local/FFV/Polylib/include/common/axis.h \
 /usr/local/FFV/Polylib/include/common/PolylibStat.h \
 /usr/local/FFV/Polylib/include/common/PolylibCommon.h \
 /usr/local/FFV/Polylib/include/common/tt.h \
 /usr/local/FFV/Polylib/include/polygons/TriMesh.h \
 /usr/local/FFV/Polylib/include/polygons/Triangle.h \
 /usr/local/FFV/Polylib/include/groups/PolygonGroup.h \
 /usr/local/FFV/TextParser/include/TextParser.h \
 /usr/local/FFV/TextParser/include/TextParserCommon.h \
 /usr/local/FFV/TextParser/include/Version.h \
 /usr/local/FFV/Polylib/include/groups/PolygonGroupFactory.h \
 /usr/local/FFV/Polylib/include/Version.h
