main.o: main.cpp ../../include/Cutlib.h /usr/local/Polylib/include/Polylib.h \
 /usr/local/Polylib/include/polygons/Polygons.h \
 /usr/local/Polylib/include/polygons/VTree.h \
 /usr/local/Polylib/include/common/BBox.h \
 /usr/local/Polylib/include/common/Vec2.h \
 /usr/local/Polylib/include/common/Vec3.h \
 /usr/local/Polylib/include/common/vec3_func.h \
 /usr/local/Polylib/include/common/vec3f_func.h \
 /usr/local/Polylib/include/common/axis.h \
 /usr/local/Polylib/include/common/PolylibStat.h \
 /usr/local/Polylib/include/common/PolylibCommon.h \
 /usr/local/Polylib/include/common/tt.h \
 /usr/local/Polylib/include/polygons/TriMesh.h \
 /usr/local/Polylib/include/polygons/Triangle.h \
 /usr/local/Polylib/include/groups/PolygonGroup.h \
 /usr/local/TextParser/include/TextParser.h \
 /usr/local/TextParser/include/TextParserCommon.h \
 /usr/local/Polylib/include/groups/PolygonGroupFactory.h \
 ../../include/RepairPolygonData/RepairPolygonData.h \
 ../../include/CutInfo/CutInfoArray.h ../../include/CutInfo/CutInfo.h \
 ../../include/CutInfo/CutNormalArray.h ../../include/Cutlib.h \
 ../../include/GridAccessor/GridAccessor.h ../../include/GridAccessor/Node.h \
 ../util/include/outputVtk.h Config.h ../util/include/ConfigBase.h \
 ../util/include/ConfigFile.h ../util/include/Tuple.h
ConfigFile.o: ../util/src/ConfigFile.cpp ../util/include/ConfigFile.h
ConfigBase.o: ../util/src/ConfigBase.cpp ../util/include/ConfigBase.h \
 ../util/include/ConfigFile.h
outputVtk.o: ../util/src/outputVtk.cpp ../util/include/outputVtk.h \
 ../../include/Cutlib.h /usr/local/Polylib/include/Polylib.h \
 /usr/local/Polylib/include/polygons/Polygons.h \
 /usr/local/Polylib/include/polygons/VTree.h \
 /usr/local/Polylib/include/common/BBox.h \
 /usr/local/Polylib/include/common/Vec2.h \
 /usr/local/Polylib/include/common/Vec3.h \
 /usr/local/Polylib/include/common/vec3_func.h \
 /usr/local/Polylib/include/common/vec3f_func.h \
 /usr/local/Polylib/include/common/axis.h \
 /usr/local/Polylib/include/common/PolylibStat.h \
 /usr/local/Polylib/include/common/PolylibCommon.h \
 /usr/local/Polylib/include/common/tt.h \
 /usr/local/Polylib/include/polygons/TriMesh.h \
 /usr/local/Polylib/include/polygons/Triangle.h \
 /usr/local/Polylib/include/groups/PolygonGroup.h \
 /usr/local/TextParser/include/TextParser.h \
 /usr/local/TextParser/include/TextParserCommon.h \
 /usr/local/Polylib/include/groups/PolygonGroupFactory.h \
 ../../include/RepairPolygonData/RepairPolygonData.h \
 ../../include/CutInfo/CutInfoArray.h ../../include/CutInfo/CutInfo.h \
 ../../include/CutInfo/CutNormalArray.h ../../include/Cutlib.h \
 ../../include/GridAccessor/GridAccessor.h
